FROM locustio/locust:latest

USER root

RUN apt-get update \
 && apt-get install -y curl make git openssh-client \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY deploy/locust-base/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER locust

ENTRYPOINT ["/entrypoint.sh"]